steps:  
  - label: "Creating our autologout functionality test app! :smile:"  
    command: "./gradlew assembleDebug"
    artifact_paths: "AutoLogout.apk"

  - label: "Debug variant tests 📏"  
    command:  
      - './gradlew testDebugUnitTest'  
      - 'tar -zcvf our-test-results.tar.gz app/build/reports/tests/testDebugUnitTest'
    artifact_paths:  
      - "app/build/reports/tests/testDebugUnitTest/index.html"
      - "app/build/reports/tests/testDebugUnitTest/our-test-results.tar.gz"
